# Generated by Django 2.2.14 on 2022-02-25 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220225_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='isReact',
        ),
        migrations.AddField(
            model_name='post',
            name='isReact',
            field=models.ManyToManyField(blank=True, related_name='isReact', to=settings.AUTH_USER_MODEL),
        ),
    ]
