# Generated by Django 2.2.14 on 2022-02-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment_react'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='react',
            field=models.IntegerField(default=0),
        ),
    ]
